# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39569449cfceb434ac4a6ae4b7453efb15a6b9bf856ecf797ece9f458738f2cfcab5d72cc136339dc029defe54065ea2a39f33a58e7f36c4978f6c597a46a97c

test:
  secret_key_base: f0c8386b6f038d42a4c085808ee372eec22b71546799ef9f4eef38afa859b04c27c5dab0cdcb5167f48015f87d0113a7cf6d244414f51bb9a2356fa1646ed245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
